version: "3.8"
services:
    frontend:
        container_name: front-end
        build:
            context: ./front-end
            dockerfile: Dockerfile.react
        image: mapuya19/sus_toxcity/frontend
        ports:
            - "3000:3000"
        volumes:
            - ./front-end:/usr/src/app/frontend
    backend:
        container_name: node_server
        build:
            context: ./node-server
            dockerfile: Dockerfile.node
        image: mapuya19/sus_toxcity/backend
        ports:
            - "8000:8000"
        volumes:
            - ./node-server:/usr/src/app
    max-classifier:
        container_name: max-classifier
        build:
            context: ./MAX-Toxic-Comment-Classifier
            dockerfile: Dockerfile.python
        image: mapuya19/sus_toxicity/max-classifier
        ports:
            - "5000:5000"
        volumes:
            - ./MAX-Toxic-Comment-Classifier:/usr/src/app/max-classifier

