version: "3.8"
services:
    frontend:
        container_name: front-end
        build:
            context: ./front-end
            dockerfile: Dockerfile
        image: mapuya19/sus_toxicity
        ports:
            - "3000:3000"
        volumes:
            - ./front-end:/usr/src/app
    backend:
        container_name: node_server
        build:
            context: ./node-server
            dockerfile: Dockerfile
        image: mapuya19/sus_toxicity
        ports:
            - "5000:5000"
        volumes:
            - ./node-server:/usr/src/app
